use_frameworks!

platform :ios, '10.0'

target 'MKLoRaWAN-BV_Example' do
  pod 'MKLoRaWAN-BV', :path => '../'

  target 'MKLoRaWAN-BV_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
